// Generated by CoffeeScript 2.3.1
(function() {
  $(document).ready(function() {
    var animate, i, item, items, len, mobile;
    $(".nav ul li a").click(function() {
      return $('html, body').animate({
        scrollTop: $(`#${$(this).attr('class')}`).offset().top
      }, 1500);
    });
    $(".chevron .down").click(function() {
      return $('html, body').animate({
        scrollTop: $("#introduction").offset().top
      }, 1500);
    });
    mobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
    if ($("html").hasClass("cssanimations") && !mobile) {
      //'#about p', 'fadeInUp', '.column', 'fadeInUp',
      //'.item', 'fadeInDown', '.bar', 'fadeInRight',
      //'.paperplane', 'bounceInDown', '#quote .content', 'fadeIn',
      //'#quote .icon', 'fadeInDown'
      animate = function(animation) {
        return $(animation[0]).addClass("concealed").viewportChecker({
          classToAdd: `visible animated ${animation[1].trim()}`,
          offset: 200
        });
      };
      items = [['#about p', 'fadeIn'], ['.column', 'fadeIn'], ['.item', 'fadeInDown'], ['.bar', 'fadeInRight'], ['.paperplane', 'bounceInDown'], ['#quote .container', 'fadeIn'], ['#quote .icon', 'fadeInDown']];
      for (i = 0, len = items.length; i < len; i++) {
        item = items[i];
        animate(item);
      }
    }
    return $("#footer ul li").hover(function() {
      return $(this).find('p').stop(true, true).fadeIn(800);
    }, function() {
      return $(this).find('p').stop(true, true).fadeOut(800);
    });
  });

}).call(this);
