# Site settings
author: Peter Schoeffman
title: Peter Schoeffman
email: schoeffman@gmail.com
description: Personal website
keywords: web, systems, analysis, computer, game
baseurl: ""
root: /
url: "http://schoeffman.com"
twitter_username: schoeffman
github_username:  schoeffman

# Build settings
markdown: kramdown
permalink: /:title
